from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1233, 799)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.image_1_2_h_layout = QtWidgets.QHBoxLayout()
        self.image_1_2_h_layout.setObjectName("image_1_2_h_layout")
        self.image_1_label = QtWidgets.QLabel(self.centralwidget)
        self.image_1_label.setText("")
        self.image_1_label.setObjectName("image_1_label")
        self.image_1_2_h_layout.addWidget(self.image_1_label)
        self.image_1_ft_label = QtWidgets.QLabel(self.centralwidget)
        self.image_1_ft_label.setText("")
        self.image_1_ft_label.setObjectName("image_1_ft_label")
        self.image_1_2_h_layout.addWidget(self.image_1_ft_label)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.image_1_2_h_layout.addWidget(self.line_3)
        self.image_2_label = QtWidgets.QLabel(self.centralwidget)
        self.image_2_label.setText("")
        self.image_2_label.setObjectName("image_2_label")
        self.image_1_2_h_layout.addWidget(self.image_2_label)
        self.image_2_ft_label = QtWidgets.QLabel(self.centralwidget)
        self.image_2_ft_label.setText("")
        self.image_2_ft_label.setObjectName("image_2_ft_label")
        self.image_1_2_h_layout.addWidget(self.image_2_ft_label)
        self.gridLayout_4.addLayout(self.image_1_2_h_layout, 0, 0, 1, 1)
        self.image_3_4_controls_layout = QtWidgets.QGridLayout()
        self.image_3_4_controls_layout.setObjectName("image_3_4_controls_layout")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.image_3_4_controls_layout.addWidget(self.line_6, 0, 5, 2, 1)
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.image_3_4_controls_layout.addWidget(self.line_12, 0, 2, 2, 1)
        self.image_3_ft_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.image_3_ft_combobox.setObjectName("image_3_ft_combobox")
        self.image_3_ft_combobox.addItem("")
        self.image_3_ft_combobox.addItem("")
        self.image_3_ft_combobox.addItem("")
        self.image_3_ft_combobox.addItem("")
        self.image_3_4_controls_layout.addWidget(self.image_3_ft_combobox, 0, 4, 2, 1)
        self.image_4_ft_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.image_4_ft_combobox.setObjectName("image_4_ft_combobox")
        self.image_4_ft_combobox.addItem("")
        self.image_4_ft_combobox.addItem("")
        self.image_4_ft_combobox.addItem("")
        self.image_4_ft_combobox.addItem("")
        self.image_3_4_controls_layout.addWidget(self.image_4_ft_combobox, 0, 10, 2, 1)
        self.image_3_ft_combobox_label = QtWidgets.QLabel(self.centralwidget)
        self.image_3_ft_combobox_label.setObjectName("image_3_ft_combobox_label")
        self.image_3_4_controls_layout.addWidget(self.image_3_ft_combobox_label, 0, 3, 2, 1)
        self.image_4_ft_combobox_label = QtWidgets.QLabel(self.centralwidget)
        self.image_4_ft_combobox_label.setObjectName("image_4_ft_combobox_label")
        self.image_3_4_controls_layout.addWidget(self.image_4_ft_combobox_label, 0, 9, 2, 1)
        self.image_4_magnitude_real_label = QtWidgets.QLabel(self.centralwidget)
        self.image_4_magnitude_real_label.setObjectName("image_4_magnitude_real_label")
        self.image_3_4_controls_layout.addWidget(self.image_4_magnitude_real_label, 0, 6, 1, 1)
        self.image_3_magnitude_real_slider = QtWidgets.QSlider(self.centralwidget)
        self.image_3_magnitude_real_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_3_magnitude_real_slider.setObjectName("image_3_magnitude_real_slider")
        self.image_3_4_controls_layout.addWidget(self.image_3_magnitude_real_slider, 0, 1, 1, 1)
        self.image_4_phase_imaginary_slider = QtWidgets.QSlider(self.centralwidget)
        self.image_4_phase_imaginary_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_4_phase_imaginary_slider.setObjectName("image_4_phase_imaginary_slider")
        self.image_3_4_controls_layout.addWidget(self.image_4_phase_imaginary_slider, 1, 7, 1, 1)
        self.image_3_magnitude_real_label = QtWidgets.QLabel(self.centralwidget)
        self.image_3_magnitude_real_label.setObjectName("image_3_magnitude_real_label")
        self.image_3_4_controls_layout.addWidget(self.image_3_magnitude_real_label, 0, 0, 1, 1)
        self.image_4_magnitude_real_slider = QtWidgets.QSlider(self.centralwidget)
        self.image_4_magnitude_real_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_4_magnitude_real_slider.setObjectName("image_4_magnitude_real_slider")
        self.image_3_4_controls_layout.addWidget(self.image_4_magnitude_real_slider, 0, 7, 1, 1)
        self.image_3_phase_imaginary_slider = QtWidgets.QSlider(self.centralwidget)
        self.image_3_phase_imaginary_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_3_phase_imaginary_slider.setObjectName("image_3_phase_imaginary_slider")
        self.image_3_4_controls_layout.addWidget(self.image_3_phase_imaginary_slider, 1, 1, 1, 1)
        self.image_4_phase_imaginary_label = QtWidgets.QLabel(self.centralwidget)
        self.image_4_phase_imaginary_label.setObjectName("image_4_phase_imaginary_label")
        self.image_3_4_controls_layout.addWidget(self.image_4_phase_imaginary_label, 1, 6, 1, 1)
        self.image_3_phase_imaginary_label = QtWidgets.QLabel(self.centralwidget)
        self.image_3_phase_imaginary_label.setObjectName("image_3_phase_imaginary_label")
        self.image_3_4_controls_layout.addWidget(self.image_3_phase_imaginary_label, 1, 0, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.image_3_4_controls_layout.addWidget(self.line_13, 0, 8, 2, 1)
        self.gridLayout_4.addLayout(self.image_3_4_controls_layout, 3, 0, 1, 1)
        self.image_1_2_controls_layout = QtWidgets.QGridLayout()
        self.image_1_2_controls_layout.setObjectName("image_1_2_controls_layout")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.image_1_2_controls_layout.addWidget(self.line_10, 0, 2, 2, 1)
        self.image_1_magnitude_real_slider = QtWidgets.QSlider(self.centralwidget)
        self.image_1_magnitude_real_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_1_magnitude_real_slider.setObjectName("image_1_magnitude_real_slider")
        self.image_1_2_controls_layout.addWidget(self.image_1_magnitude_real_slider, 0, 1, 1, 1)
        self.image_2_ft_combobox_label = QtWidgets.QLabel(self.centralwidget)
        self.image_2_ft_combobox_label.setObjectName("image_2_ft_combobox_label")
        self.image_1_2_controls_layout.addWidget(self.image_2_ft_combobox_label, 0, 9, 2, 1)
        self.image_2_magnitude_real_label = QtWidgets.QLabel(self.centralwidget)
        self.image_2_magnitude_real_label.setObjectName("image_2_magnitude_real_label")
        self.image_1_2_controls_layout.addWidget(self.image_2_magnitude_real_label, 0, 6, 1, 1)
        self.image_2_phase_imaginary_label = QtWidgets.QLabel(self.centralwidget)
        self.image_2_phase_imaginary_label.setObjectName("image_2_phase_imaginary_label")
        self.image_1_2_controls_layout.addWidget(self.image_2_phase_imaginary_label, 1, 6, 1, 1)
        self.image_1_magnitude_real_label = QtWidgets.QLabel(self.centralwidget)
        self.image_1_magnitude_real_label.setObjectName("image_1_magnitude_real_label")
        self.image_1_2_controls_layout.addWidget(self.image_1_magnitude_real_label, 0, 0, 1, 1)
        self.image_1_phase_imaginary_label = QtWidgets.QLabel(self.centralwidget)
        self.image_1_phase_imaginary_label.setObjectName("image_1_phase_imaginary_label")
        self.image_1_2_controls_layout.addWidget(self.image_1_phase_imaginary_label, 1, 0, 1, 1)
        self.image_2_phase_imaginary_slider = QtWidgets.QSlider(self.centralwidget)
        self.image_2_phase_imaginary_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_2_phase_imaginary_slider.setObjectName("image_2_phase_imaginary_slider")
        self.image_1_2_controls_layout.addWidget(self.image_2_phase_imaginary_slider, 1, 7, 1, 1)
        self.image_1_phase_imaginary_slider = QtWidgets.QSlider(self.centralwidget)
        self.image_1_phase_imaginary_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_1_phase_imaginary_slider.setObjectName("image_1_phase_imaginary_slider")
        self.image_1_2_controls_layout.addWidget(self.image_1_phase_imaginary_slider, 1, 1, 1, 1)
        self.image_2_ft_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.image_2_ft_combobox.setObjectName("image_2_ft_combobox")
        self.image_2_ft_combobox.addItem("")
        self.image_2_ft_combobox.addItem("")
        self.image_2_ft_combobox.addItem("")
        self.image_2_ft_combobox.addItem("")
        self.image_1_2_controls_layout.addWidget(self.image_2_ft_combobox, 0, 10, 2, 1)
        self.image_2_magnitude_real_slider = QtWidgets.QSlider(self.centralwidget)
        self.image_2_magnitude_real_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_2_magnitude_real_slider.setObjectName("image_2_magnitude_real_slider")
        self.image_1_2_controls_layout.addWidget(self.image_2_magnitude_real_slider, 0, 7, 1, 1)
        self.image_1_ft_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.image_1_ft_combobox.setObjectName("image_1_ft_combobox")
        self.image_1_ft_combobox.addItem("")
        self.image_1_ft_combobox.addItem("")
        self.image_1_ft_combobox.addItem("")
        self.image_1_ft_combobox.addItem("")
        self.image_1_2_controls_layout.addWidget(self.image_1_ft_combobox, 0, 4, 2, 1)
        self.image_1_ft_combobox_label = QtWidgets.QLabel(self.centralwidget)
        self.image_1_ft_combobox_label.setObjectName("image_1_ft_combobox_label")
        self.image_1_2_controls_layout.addWidget(self.image_1_ft_combobox_label, 0, 3, 2, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.image_1_2_controls_layout.addWidget(self.line_4, 0, 5, 2, 1)
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.image_1_2_controls_layout.addWidget(self.line_11, 0, 8, 2, 1)
        self.gridLayout_4.addLayout(self.image_1_2_controls_layout, 1, 0, 1, 1)
        self.image_2_3_h_layout = QtWidgets.QHBoxLayout()
        self.image_2_3_h_layout.setObjectName("image_2_3_h_layout")
        self.image_3_label = QtWidgets.QLabel(self.centralwidget)
        self.image_3_label.setText("")
        self.image_3_label.setObjectName("image_3_label")
        self.image_2_3_h_layout.addWidget(self.image_3_label)
        self.image_3_ft_label = QtWidgets.QLabel(self.centralwidget)
        self.image_3_ft_label.setText("")
        self.image_3_ft_label.setObjectName("image_3_ft_label")
        self.image_2_3_h_layout.addWidget(self.image_3_ft_label)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.image_2_3_h_layout.addWidget(self.line_5)
        self.image_4_label = QtWidgets.QLabel(self.centralwidget)
        self.image_4_label.setText("")
        self.image_4_label.setObjectName("image_4_label")
        self.image_2_3_h_layout.addWidget(self.image_4_label)
        self.image_4_ft_label = QtWidgets.QLabel(self.centralwidget)
        self.image_4_ft_label.setText("")
        self.image_4_ft_label.setObjectName("image_4_ft_label")
        self.image_2_3_h_layout.addWidget(self.image_4_ft_label)
        self.gridLayout_4.addLayout(self.image_2_3_h_layout, 2, 0, 1, 1)
        self.output_v_layout = QtWidgets.QVBoxLayout()
        self.output_v_layout.setObjectName("output_v_layout")
        self.output_1_label = QtWidgets.QLabel(self.centralwidget)
        self.output_1_label.setText("")
        self.output_1_label.setObjectName("output_1_label")
        self.output_v_layout.addWidget(self.output_1_label)
        self.output_1_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.output_1_checkbox.setObjectName("output_1_checkbox")
        self.output_v_layout.addWidget(self.output_1_checkbox)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.output_v_layout.addWidget(self.line_8)
        self.output_2_label = QtWidgets.QLabel(self.centralwidget)
        self.output_2_label.setText("")
        self.output_2_label.setObjectName("output_2_label")
        self.output_v_layout.addWidget(self.output_2_label)
        self.output_2_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.output_2_checkbox.setObjectName("output_2_checkbox")
        self.output_v_layout.addWidget(self.output_2_checkbox)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.output_v_layout.addWidget(self.line_2)
        self.gridLayout_4.addLayout(self.output_v_layout, 0, 2, 3, 1)
        self.main_controls_layout = QtWidgets.QGridLayout()
        self.main_controls_layout.setObjectName("main_controls_layout")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.main_controls_layout.addWidget(self.line_7, 0, 4, 1, 1)
        self.select_region_label = QtWidgets.QLabel(self.centralwidget)
        self.select_region_label.setObjectName("select_region_label")
        self.main_controls_layout.addWidget(self.select_region_label, 0, 2, 1, 1)
        self.select_region_label_2 = QtWidgets.QSlider(self.centralwidget)
        self.select_region_label_2.setOrientation(QtCore.Qt.Horizontal)
        self.select_region_label_2.setObjectName("select_region_label_2")
        self.main_controls_layout.addWidget(self.select_region_label_2, 0, 3, 1, 1)
        self.ft_pairs_combobox = QtWidgets.QComboBox(self.centralwidget)
        self.ft_pairs_combobox.setObjectName("ft_pairs_combobox")
        self.ft_pairs_combobox.addItem("")
        self.ft_pairs_combobox.addItem("")
        self.main_controls_layout.addWidget(self.ft_pairs_combobox, 0, 6, 1, 1)
        self.mix_button = QtWidgets.QPushButton(self.centralwidget)
        self.mix_button.setObjectName("mix_button")
        self.main_controls_layout.addWidget(self.mix_button, 0, 0, 1, 1)
        self.ft_pairs_label = QtWidgets.QLabel(self.centralwidget)
        self.ft_pairs_label.setObjectName("ft_pairs_label")
        self.main_controls_layout.addWidget(self.ft_pairs_label, 0, 5, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.main_controls_layout.addWidget(self.line_9, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.main_controls_layout, 3, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 0, 1, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1233, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("FT Image Mixer", "FT Image Mixer"))
        self.image_3_ft_combobox.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.image_3_ft_combobox.setItemText(1, _translate("MainWindow", "Phase"))
        self.image_3_ft_combobox.setItemText(2, _translate("MainWindow", "Real"))
        self.image_3_ft_combobox.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.image_4_ft_combobox.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.image_4_ft_combobox.setItemText(1, _translate("MainWindow", "Phase"))
        self.image_4_ft_combobox.setItemText(2, _translate("MainWindow", "Real"))
        self.image_4_ft_combobox.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.image_3_ft_combobox_label.setText(_translate("MainWindow", "FT Component"))
        self.image_4_ft_combobox_label.setText(_translate("MainWindow", "FT Component"))
        self.image_4_magnitude_real_label.setText(_translate("MainWindow", "Magnitude"))
        self.image_3_magnitude_real_label.setText(_translate("MainWindow", "Magnitude"))
        self.image_4_phase_imaginary_label.setText(_translate("MainWindow", "Phase"))
        self.image_3_phase_imaginary_label.setText(_translate("MainWindow", "Phase"))
        self.image_2_ft_combobox_label.setText(_translate("MainWindow", "FT Componet"))
        self.image_2_magnitude_real_label.setText(_translate("MainWindow", "Magnitude"))
        self.image_2_phase_imaginary_label.setText(_translate("MainWindow", "Phase"))
        self.image_1_magnitude_real_label.setText(_translate("MainWindow", "Magnitude"))
        self.image_1_phase_imaginary_label.setText(_translate("MainWindow", "Phase"))
        self.image_2_ft_combobox.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.image_2_ft_combobox.setItemText(1, _translate("MainWindow", "Phase"))
        self.image_2_ft_combobox.setItemText(2, _translate("MainWindow", "Real"))
        self.image_2_ft_combobox.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.image_1_ft_combobox.setItemText(0, _translate("MainWindow", "Magnitude"))
        self.image_1_ft_combobox.setItemText(1, _translate("MainWindow", "Phase"))
        self.image_1_ft_combobox.setItemText(2, _translate("MainWindow", "Real"))
        self.image_1_ft_combobox.setItemText(3, _translate("MainWindow", "Imaginary"))
        self.image_1_ft_combobox_label.setText(_translate("MainWindow", "FT Component"))
        self.output_1_checkbox.setText(_translate("MainWindow", "Show"))
        self.output_2_checkbox.setText(_translate("MainWindow", "Show"))
        self.select_region_label.setText(_translate("MainWindow", "Region:"))
        self.ft_pairs_combobox.setItemText(0, _translate("MainWindow", "Magnitude and Phase"))
        self.ft_pairs_combobox.setItemText(1, _translate("MainWindow", "Real and Imaginary"))
        self.mix_button.setText(_translate("MainWindow", "Mix"))
        self.ft_pairs_label.setText(_translate("MainWindow", "FT Pairs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
